app/urls.py
from django.urls import path
from .views import (
    HomePageView, dashboard, create_article, all_articles, delete_article, edit_article, all_videos, all_appointments, booked_appointments, create_appointment, schedule_appointment, edit_appointment, delete_appointment
)
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('dashboard', dashboard, name='dashboard'),
    path('articles', all_articles, name='articles'),
    path('articles/create', create_article, name='create_article'),
    path('articles/edit/<slug:slug>', edit_article, name='edit_article'),
    path('articles/delete/<slug:slug>', delete_article, name='delete_article'),
    path('appointments', all_appointments, name='appointments'),
    path('booked_appointments', booked_appointments, name='booked_appointments'),
    path('appointment/create', create_appointment, name='create_appointment'),
    path('appointment/edit/<slug:slug>', edit_appointment, name='edit_appointment'),
    path('appointment/schedule/<slug:slug>', schedule_appointment, name='schedule_appointment'),
    path('appointment/delete/<slug:slug>', delete_appointment, name='delete_appointment'),
    path('videos', all_videos, name='videos'),
]

chat/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('chat/', views.chat_view, name='chats'),
    path('chat/<int:sender>/<int:receiver>/', views.view_message, name='chat'),
    path('api/messages/<int:sender>/<int:receiver>/', views.get_send_message, name='message-detail'),
    path('api/messages/', views.get_send_message, name='message-list'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('users.urls')),
    path('', include('chat.urls')),
]

chat/models.py
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.db import models


class Message(models.Model):
    sender = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)

chat/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from users.models import CustomUser
from django.http.response import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from .models import Message
from chat.serializers import MessageSerializer
from django.contrib.auth.decorators import login_required


@login_required(login_url='login')
@csrf_exempt
def get_send_message(request, sender=None, receiver=None):
    """
    gets all messages, and create a new message
    """
    if request.method == 'GET':
        messages = Message.objects.filter(sender_id=sender, receiver_id=receiver, is_read=False)
        serializer = MessageSerializer(messages, many=True, context={'request': request})
        for message in messages:
            message.is_read = True
            message.save()
        return JsonResponse(serializer.data, safe=False)
    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = MessageSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)

@login_required(login_url='login')
def chat_view(request):
    if request.method == "GET":
        unread_chats_count, unread_chats = 0, {}
        for user in CustomUser.objects.all():
            chats = Message.objects.filter(sender=user, is_read=False).count()
            unread_chats_count += chats
            unread_chats.update({user.first_name: chats})

        return render(request, 'chat.html', {"users": CustomUser.objects.exclude(first_name=request.user.first_name), "unread_chats":unread_chats})

@login_required(login_url='login')
def view_message(request, sender, receiver):
    if request.method == "GET":
        unread_chats_count, unread_chats = 0, {}
        for user in CustomUser.objects.all():
            chats = Message.objects.filter(sender=user, is_read=False).count()
            unread_chats_count += chats
            unread_chats.update({user.first_name: chats})

        return render(request, "messages.html",
            {
                'users': CustomUser.objects.exclude(first_name=request.user.first_name).order_by('first_name'),
                'receiver': CustomUser.objects.get(id=receiver),
                'messages': Message.objects.filter(sender_id=sender, receiver_id=receiver) | Message.objects.filter(sender_id=receiver, receiver_id=sender),
                'unread_chats': unread_chats
            }
        )

templates/admin_chats.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}" media="screen,projection" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}" media="screen,projection" />

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/chat.js' %}"></script>
</head>

<body>
    {% block body %}
    <nav class="lighten-3" style="background-color: gray">
        <div class="nav-wrapper container">
            <a href="#" class="brand-logo">Chat</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="">{{ request.user.first_name }}</a></li>
                <li><a href="{% url 'logout' %}"><i class="material-icons">power_settings_new</i></a></li>
            </ul>
        </div>
    </nav>
    <div class="section" style="height: 80vh">
        <div class="row">
            <div class="col s3">
                <div class="card">
                    <div class="collection">
                        {% for user in users %}
                        <a href="{% url 'chat' request.user.id user.id %}" id="user{{ user.id }}"
                            class="collection-item row">
                            <img src="https://frontend-1.adjust.com/new-assets/images/site-images/interface/user.svg"
                                class="col s4">
                            <div class="col s8">
                                <span class="title" style="font-weight: bolder">{{ user.first_name }}</span>
                            </div>
                        </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col s9">
                <div class="card">
                    <div id="board" class="section grey lighten-3"
                        style="height: 68vh; padding: 5px; overflow-y: scroll">
                        {% block messages %}

                        {% endblock %}
                    </div>
                    <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col s11">
                                <div class="input-field">
                                    <input id="id_message" name="message" type="text" placeholder="Type your message..">
                                </div>
                            </div>
                            <div class="col s1" style="line-height: 80px">
                                <button class="btn btn-floating lighten-2 waves-effect waves-light"
                                    style="background-color: gray"><i class="material-icons">send</i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/chat.js' %}"></script>
    <script>
        // For receiving
        sender_id = "{{ receiver.id }}";
        receiver_id = "{{ request.user.id }}";

        //For sending
        $(function () {
            scrolltoend();
            $('#chat-box').on('submit', function (event) {
                event.preventDefault();
                var message = $('#id_message');
                send('{{ request.user.first_name }}', '{{ receiver.first_name }}', message.val());
                message.val('');
            })
        })
    </script>
    {% endblock %}
</body>

</html>

templates/appointments.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Appointment Slots - TU Counsel{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/all_appointments.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/109fe23f15.js" crossorigin="anonymous"></script>
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
</head>

<body>
    {% include 'sidebar.html' %}
    <section class="home-section" style="background-color: white;" id="btn">
        <h2>Appointment Slots</h2>
        <div id="appointments_wrapper">
            {% for appointment in appointments %}
                <h3 class="dates">{{ appointment.date }}</h3>
                {% if request.user.is_superuser %}
                    {% if appointment.session_type %}
                    <a href="{% url 'booked_appointments' %}" class="appts_link">
                        <div class="appt_card" style="background: rgb(44, 243, 183); cursor: pointer;">
                            <p class="booked_tag">Booked</p>
                            <p class="appt_time">
                                {{appointment.start_time}} - {{appointment.end_time }}
                            </p>
                        </div>
                    </a>
                    {% else %}
                        <div class="appt_card greyed_out">
                            <p class="notbooked_tag">Available</p>
                            <p class="appt_time">
                                {{appointment.start_time}} - {{appointment.end_time }}
                            </p>
                            <p class="edit_icon" style="background: rgb(63, 63, 63);">
                                <a href="{% url 'edit_appointment' appointment.slug %}" style="color: rgb(255, 255, 255);">Edit <i class="bx bxs-edit-alt"></i></a>
                            </p> 
                        </div>
                    {% endif %}
                {% else %}
                    {% if appointment.session_type %}
                        <div class="appt_card greyed_out">
                            {% if appointment.booked_by == request.user %}
                            <p class="booked_tag">Booked by you</p>
                            {% else %}
                            <p class="booked_tag">Booked</p>
                            {% endif %}
                            <p class="appt_time">
                                {{appointment.start_time}} - {{appointment.end_time }}
                            </p>
                        </div>
                    {% else %}
                        <div class="appt_card" style="background: rgb(44, 243, 183);">
                            <p class="notbooked_tag" style="background: rgb(4, 124, 88);">Available</p>
                            <p class="appt_time">
                                {{appointment.start_time}} - {{appointment.end_time }}
                            </p>
                            <p class="edit_icon" style="background: white;">
                                <a href="{% url 'schedule_appointment' appointment.slug %}" style="color: rgb(0, 0, 0);">Schedule<i class="bx bx-list-check"></i></a>
                            </p> 
                        </div>
                    {% endif %}
                {% endif %}
                <hr>
            {% endfor %}
        </div>

    </section>
</body>
<!-- <script src="{% static 'js/script.js' %}"></script> -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>

</html>

templates/articles.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Articles - TU Counsel{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/articleslist.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/109fe23f15.js" crossorigin="anonymous"></script>
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
    <!-- <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicons/apple-touch-icon.png' %}">
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicons/favicon-32x32.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicons/favicon-16x16.png' %}">
	<link rel="manifest" href="{% static 'favicons/site.webmanifest' %}"> -->
</head>

<body>
    
    {% include 'sidebar.html' %}
    <section class="home-section" style="background-color: white;" id="btn;">
        <form method="GET" id="searchbar">
            <div id="search_btn" class="bx bx-search"></div>
            <input name="search-area" type="search" placeholder="Search articles..." id="search_input"/>
        </form>
        <hr style="width:
        60%; margin: 30px auto;">
        <section id="articles_main">
            <div id="article_reader">
            </div>
            <div id="article_grid_wrapper">
                <div id="mobile_reader"></div>
                <div id="expand_grid"> &#8592; Close article</div>
                <div id="article_grid">
                    {% for article in articles %}
                    <div class="card-article" 
                    onclick="showArticle('{{ article.title }}', '{{ article.tags }}', '{{ article.image_url }}')">
                    <p style="display: none;" class="content_parameter">{{ article.content }}&s#3DEMACATION{{ article.title }}</p>
                        {% if article.image_url %}
                        <img src={{article.image_url}} alt="">
                        {% endif %}
                        <div class="title_lnk">
                        <p class="article-title">{{ article.title|truncatechars:45 }}</p>
                        
                        {% if request.user.is_superuser %}
                        <a href="{% url 'edit_article' article.slug %}" class="edit_lnk">Edit</a>
                        {% else %}
                        {% endif %}
                        </div>
                        <div class="article_tags">{{ article.tags }}</div>
                        <p class="article-intro">{{ article.content|truncatechars:60 }}</p>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </section>
    </section>
</body>
<script src="{% static 'js/articleslist.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
</html>

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="TU Counsel is an app for counselling">
    <meta name="keywords" content="Counselling, Counsel">
    <title>
        {% block title %}TU Counsel: App for counselling, tutoring, mentoring{% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
    <!-- <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicons/site.webmanifest' %}"> -->

</head>

<body>
    {% include 'navbar.html' %}
    <main>
        {% block content %}
        {% endblock content %}
    </main>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>

templates/create_appointment.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Create Appointment Slot - TU Counsel{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/createappointment.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/109fe23f15.js" crossorigin="anonymous"></script>
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/material_green.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
</head>

<body>
    {% include 'sidebar.html' %}
    <section class="home-section" style="background-color: white;">
        <h4>Create Appointment Slot</h4>
        <div id="appointment_form" class="card">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success" box-shadow="none">Save</button>
                    <button type="button" class="btn btn-danger"><a href="{% url 'dashboard' %}"
                            style="text-decoration: none; color: white;" box-shadow="none">Cancel</a></button>
                </form>
            </div>
        </div>
    </section>
</body>
<script>
    flatpickr('input[type="date"]', {});
    flatpickr('input[type="time"]', {
        enableTime: true,
        noCalendar: true,
        dateFormat: "H:i",
        minTime: "08:00",
        maxTime: "20:00",
    });
</script>
<!-- <script src="{% static 'js/script.js' %}"></script> -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>

</html>

templates/create_article.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Publish an Article - TU Counsel{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/articles.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/109fe23f15.js" crossorigin="anonymous"></script>
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
</head>

<body>
    {% include 'sidebar.html' %}
    <section class="home-section" style="background-color: white;">
        <h4 style="text-align: center; padding: 10px 0; font-size: 2em;">Publish an Article</h4>
        <div id="article_form">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div id="form_btns">
                        <button type="submit" class="btn btn-success" box-shadow="none">Save</button>
                        <a href="{% url 'dashboard' %}" style="text-decoration: none; color: white;" box-shadow="none"><button type="button" class="btn btn-danger">Cancel</button></a>
                    </div>
                    </form>
            </div>
        </div>
    </section>
</body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
</html>

templates/edit_appointment.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Edit Appointment Slot - TU Counsel{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/createappointment.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/109fe23f15.js" crossorigin="anonymous"></script>
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/material_green.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
</head>

<body>
    {% include 'sidebar.html' %}
    <section class="home-section" style="background-color: white;">
        <h4>Edit Appointment</h4>
        <div id="appointment_form" class="card">
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success" box-shadow="none">Update</button>
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal"
                        box-shadow="none"><a style="text-decoration: none; color: white;">Delete</a></button>
                </form>
            </div>
        </div>
    </section>

    <!-- Delete Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <i class='bx bx-x' box-shadow="none" data-bs-dismiss="modal"
                        style="font-size: 34px; margin-left: 420px;"></i>
                </div>
                <div class="modal-body">
                    <b>Are you sure you want to delete this appointment?</b>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal"><a
                            href="{% url 'delete_appointment' slug=form.instance.slug %}"
                            style="text-decoration: none; color: white;" box-shadow="none">Yes</a></button>
                    <button type="button" class="btn btn-light" box-shadow="none" data-bs-dismiss="modal"
                        style="background-color: transparent; border: 1px solid black;"><a
                            style="text-decoration: none; color: black;">No</a></button>
                </div>
            </div>
        </div>
    </div>
    
    <script>
        flatpickr('input[type="date"]', {});
        flatpickr('input[type="time"]', {
            enableTime: true,
            noCalendar: true,
            dateFormat: "H:i",
            minTime: "08:00",
            maxTime: "20:00",
        });
        setTimeout(function () {
            if ($('#alert_msg').length > 0) {
                $('#alert_msg').remove();
            }
        }, 8000)
    </script>
    <!-- <script src="{% static 'js/script.js' %}"></script> -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>